services:
  jenkins:
    build:
      context: ./conf/jenkins
      args:
        DOCKER_GID: 998
        GID: ${GID}
        UID: ${UID}
    container_name: jenkins
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
    networks:
      - union
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/jenkins:/var/jenkins_home

networks:
  union:
    external: true
