services:
  jenkins:
    container_name: jenkins
    restart: unless-stopped
    image: jenkins/jenkins:2.375.3-lts-slim
    environment:
      TZ: ${TZ}
      JENKINS_OPTS: "--prefix=/jenkins"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker
      - ./data/jenkins:/var/jenkins_home
