services:
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
    ports:
    - 27017:27017
    volumes:
    - ./data/mongo:/data/db
