services:
  mosdns:
    container_name: mosdns
    restart: unless-stopped
    image: irinesistiana/mosdns:v4.5.3
    environment:
      TZ: ${TZ}
    ports:
      - 5353:53/tcp
      - 5353:53/udp
    volumes:
      - ./data/mosdns:/etc/mosdns
    entrypoint: /etc/mosdns/entrypoint.sh
