services:
  mosdns:
    container_name: mosdns
    restart: unless-stopped
    build: ./conf/mosdns
    ports:
    - 5353:5353/udp
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./data/mosdns:/etc/mosdns
