services:
  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:8.0
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
    ports:
      - 3306:3306
    cap_add:
      - CAP_SYS_NICE
    volumes:
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
