services:
  nextcloud:
    depends_on:
      - nextcloud_db
    container_name: nextcloud
    restart: unless-stopped
    build:
      context: ./conf/nextcloud
    environment:
      TZ: ${TZ}
      NEXTCLOUD_ADMIN_USER: ${USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${COMPANY_HOST}
      APACHE_DISABLE_REWRITE_IP: "1"
      TRUSTED_PROXIES: ${DOCKER_COMPANY_SUBNET}
      POSTGRES_HOST: nextcloud_db
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: "123123"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_USERNAME}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
    volumes:
      - ./data/nextcloud/data:/var/www/html
  nextcloud_db:
    container_name: nextcloud_db
    restart: unless-stopped
    image: postgres:14.2
    environment:
      TZ: ${TZ}
      POSTGRES_USER: nextcloud
      POSTGRES_DB: nextcloud
      POSTGRES_PASSWORD: "123123"
    volumes:
      - ./data/nextcloud/db:/var/lib/postgresql/data
