services:
  nginx:
    container_name: nginx
    restart: on-failure:3
    image: nginx:1.21
    networks:
      - union
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx/data:/var/www

networks:
  union:
    external: true
