services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.21
    environment:
      TZ: ${TZ}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx/data:/var/www
