services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:10
    environment:
      TZ: ${TZ}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
