services:
  postgres:
    container_name: postgres
    restart: on-failure:3
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    networks:
      - union
    ports:
      - '5432:5432'
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/postgresql:/var/lib/postgresql/data

networks:
  union:
    external: true
