services:
  prometheus:
    container_name: prometheus
    restart: on-failure:3
    image: prom/prometheus
    networks:
      - union
    volumes:
      - ./data/project-monitor/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    restart: on-failure:3
    image: grafana/grafana
    networks:
      - union

networks:
  union:
    external: true
