services:
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus
    volumes:
    - ./data/project-monitor/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    depends_on:
    - prometheus
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
