services:
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:6.2
    environment:
      TZ: ${TZ}
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/conf:/usr/local/etc/redis
      - ./data/redis/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
