services:
  tengine:
    container_name: tengine
    restart: unless-stopped
    build:
      context: ./conf/tengine
      args:
        TENGINE_VERSION: 2.4.0
    environment:
      TZ: ${TZ}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx/data:/var/www
